server:
  port: 12000
  servlet:
    context-path: /
  #  gzip 开启
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: xuegao-im-manage
  servlet:
    multipart:
      #      文件上传单次的大小，
      max-file-size: 10MB
      max-request-size: 100MB



